name: Auto Visit Website
on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  visit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Create package.json
        run: |
          echo '{
            "name": "bloghelper",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "node visit.js"
            }
          }' > package.json
          
      - name: Install Puppeteer
        run: npm install puppeteer@latest
          
      - name: Run visit script
        run: node visit.js
