name: Auto Visit Website
on:
  schedule:
    - cron: "*/20 * * * *"  # 每20分钟运行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  visit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer@latest
          
      - name: Run visit script
        run: node visit.js
