name: Sync Fork

on:
  schedule:
    # 每天运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3

      - name: Add upstream repository
        run: git remote add upstream https://github.com/GZC888/bloghelper.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes
        run: git push origin main
